# Generated by Django 3.1.7 on 2021-03-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bloqueado',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
