# Generated by Django 3.1.7 on 2021-02-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=100)),
                ('imagenServicio', models.ImageField(blank=True, null=True, upload_to='servicios')),
                ('descripcionServicio', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
