# Generated by Django 3.1.7 on 2021-02-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descripcionServicio',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagenServicio',
            field=models.ImageField(blank=True, null=True, upload_to='servicios', verbose_name='imgagen'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreServicio',
            field=models.CharField(max_length=100, verbose_name='servicio'),
        ),
    ]
