# Generated by Django 3.1.7 on 2021-02-27 18:30

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('servicio', '0002_auto_20210227_1230'),
        ('cliente', '0002_auto_20210227_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['lugar'], 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicios',
            field=models.ManyToManyField(to='servicio.Servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidoMaterno',
            field=models.CharField(max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidoPaterno',
            field=models.CharField(max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comentariosCliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lugarNacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.entidad',
                                    verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=50, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nss',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True,
                                              validators=[django.core.validators.MaxValueValidator(99999999999)],
                                              verbose_name='Número de seguridad social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Teléfono'),
        ),
    ]
