# Generated by Django 3.1.7 on 2021-02-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cliente', '0004_auto_20210227_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Teléfono'),
        ),
    ]
