# Generated by Django 3.1.7 on 2021-02-28 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cliente', '0005_auto_20210227_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999),
                                                          django.core.validators.MinLengthValidator(10)],
                                              verbose_name='Teléfono'),
        ),
    ]
