# Generated by Django 3.1.7 on 2021-02-28 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cliente', '0006_auto_20210227_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[
                django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format '+123456789'. Up to 10 digits allowed.",
                    regex='^\\+?1?\\d{10}$')]),
        ),
    ]
