# Generated by Django 3.1.7 on 2021-02-28 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cliente', '0007_auto_20210227_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=4922284598, max_length=10, validators=[django.core.validators.RegexValidator(
                message="Phone number must be entered in the format '+123456789'. Up to 10 digits allowed.",
                regex='^\\+?1?\\d{10}$')]),
            preserve_default=False,
        ),
    ]
