# Generated by Django 3.1.7 on 2021-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cliente', '0008_auto_20210227_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
